import type { ApplicationType } from 'digital-planning-data-schemas/types/schemas/prototypeApplication/enums/ApplicationType.ts'
import type { PrimaryApplicationType } from 'digital-planning-data-schemas/types/schemas/prototypeApplication/enums/ApplicationType.ts'

/**
 * List of valid application types based on ApplicationType
 */
export const validApplicationTypes: Record<
  PrimaryApplicationType,
  ApplicationType[]
> = {
  advertConsent: ['advertConsent'],
  amendment: ['amendment', 'amendment.minorMaterial', 'amendment.nonMaterial'],
  approval: ['approval', 'approval.conditions', 'approval.reservedMatters'],
  complianceConfirmation: ['complianceConfirmation'],
  environmentalImpact: [
    'environmentalImpact',
    'environmentalImpact.scoping',
    'environmentalImpact.screening'
  ],
  hazardousSubstanceConsent: ['hazardousSubstanceConsent'],
  hedgerowRemovalNotice: ['hedgerowRemovalNotice'],
  landDrainageConsent: ['landDrainageConsent'],
  ldc: [
    'ldc',
    'ldc.breachOfCondition',
    'ldc.existing',
    'ldc.listedBuildingWorks',
    'ldc.proposed'
  ],
  listed: ['listed'],
  notifyCompletion: ['notifyCompletion'],
  obligation: ['obligation', 'obligation.discharge', 'obligation.modify'],
  onshoreExtractionOilAndGas: [
    'onshoreExtractionOilAndGas',
    'onshoreExtractionOilAndGas.other',
    'onshoreExtractionOilAndGas.pp.extension',
    'onshoreExtractionOilAndGas.pp.waste',
    'onshoreExtractionOilAndGas.pp.working',
    'onshoreExtractionOilAndGas.review',
    'onshoreExtractionOilAndGas.variation'
  ],
  pa: [
    'pa',
    'pa.part1.classA',
    'pa.part1.classAA',
    'pa.part3.classG',
    'pa.part3.classM',
    'pa.part3.classMA',
    'pa.part3.classN',
    'pa.part3.classQ',
    'pa.part3.classR',
    'pa.part3.classS',
    'pa.part3.classT',
    'pa.part3.classV',
    'pa.part4.classBB',
    'pa.part4.classBC',
    'pa.part4.classCA',
    'pa.part4.classE',
    'pa.part6',
    'pa.part6.classA',
    'pa.part6.classB',
    'pa.part6.classE',
    'pa.part7.classC',
    'pa.part7.classM',
    'pa.part9.classD',
    'pa.part11.classB',
    'pa.part14.classA',
    'pa.part14.classB',
    'pa.part14.classJ',
    'pa.part14.classK',
    'pa.part14.classOA',
    'pa.part16.classA',
    'pa.part17',
    'pa.part17.classB',
    'pa.part17.classC',
    'pa.part17.classG',
    'pa.part18.classA',
    'pa.part19.classTA',
    'pa.part20.classA',
    'pa.part20.classAA',
    'pa.part20.classAB',
    'pa.part20.classAC',
    'pa.part20.classAD',
    'pa.part20.classZA'
  ],
  pp: [
    'pp',
    'pp.full',
    'pp.full.advertConsent',
    'pp.full.demolition',
    'pp.full.fastTrack.affordable',
    'pp.full.householder',
    'pp.full.householder.listed',
    'pp.full.householder.retro',
    'pp.full.major',
    'pp.full.major.technicalDetails',
    'pp.full.major.technicalDetails.waste',
    'pp.full.major.waste',
    'pp.full.minor',
    'pp.full.minor.listed',
    'pp.full.minor.technicalDetails',
    'pp.mineralExtraction',
    'pp.outline',
    'pp.outline.all',
    'pp.outline.some',
    'pp.outline.minor',
    'pp.outline.minor.all',
    'pp.outline.minor.some',
    'pp.outline.major',
    'pp.outline.major.all',
    'pp.outline.major.all.waste',
    'pp.outline.major.some',
    'pp.outline.major.some.waste',
    'pp.pip'
  ],
  rightsOfWayOrder: ['rightsOfWayOrder'],
  wtt: ['wtt', 'wtt.consent', 'wtt.notice']
}
