services:
  dpr-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dpr}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-dpr}
    ports:
      - 5433:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - dpr-network

volumes:
  postgres-volume:

networks:
  dpr-network:
    name: dpr-network
