services:
  mock-bucket:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    ports:
      - '10000:10000'
      - '10001:10001'
      - '10002:10002'
    # volumes:
    #   - ./data:/data
    networks:
      - dpr-tools

networks:
  dpr-tools:
    external: true
