-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2025-07-28T14:55:41.242Z

CREATE TABLE "planning_applications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference" varchar(50) UNIQUE,
  "address" text,
  "postcode" text,
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp,
  "consultation_start_date" timestamp,
  "consultation_end_date" timestamp,
  "latitude" float,
  "longitude" float,
  "radius" integer
);
