Table planning_applications {
  id integer [pk, increment]
  reference varchar(50) [unique, not null]
  address text
  postcode text
  description text
  created_at timestamp
  updated_at timestamp
}
