-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2025-07-25T11:24:20.499Z

CREATE TABLE "planning_applications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference" varchar(50) UNIQUE NOT NULL,
  "address" text,
  "postcode" text,
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);
