name: Run performance tests

# on:
#   push:
#     branches:
#       - main
#       - hn/add-ci

jobs:
  artillery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: lts/jod

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn workspace @product/api run generate

      - name: Run the project
        run: yarn workspace @product/api run start &

      - name: Wait for API to be ready
        run: npx wait-on http://localhost:4000

      - name: Execute load tests
        uses: artilleryio/action-cli@v1
        with:
          command: run performance.yml
          working-directory: ./product/api

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artillery-report
          path: ./report.json # reference the generated report in the file system
